<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>GodjoLauncher</AssemblyName>
    <RootNamespace>GodjoLauncher</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>2.0.0</Version>
    <Product>Godjo Role Play Launcher</Product>
    <Company>Godjo Role Play</Company>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
    <PackageReference Include="System.IO.Hashing" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ui\index.html" LogicalName="ui.index.html" />
    <EmbeddedResource Include="app.ico" LogicalName="app.ico" />
  </ItemGroup>
</Project>
