-- Godjo Role Play — схема SQLite. Выполняется сервером автоматически при старте.
-- Каждая команда заканчивается ';' в конце строки. Строки не длиннее 250 символов.
CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, v TEXT);
CREATE TABLE IF NOT EXISTS accounts (
 id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE COLLATE NOCASE, pass TEXT, salt TEXT,
 email TEXT, ref_by TEXT DEFAULT '', reg_ip TEXT, reg_date TEXT, last_login TEXT, last_ip TEXT,
 admin INTEGER DEFAULT 0, sex INTEGER DEFAULT 0, skin INTEGER DEFAULT 78, age INTEGER DEFAULT 25,
 origin INTEGER DEFAULT 0, level INTEGER DEFAULT 1, exp INTEGER DEFAULT 0, cash INTEGER DEFAULT 0,
 bank INTEGER DEFAULT 0, hunger REAL DEFAULT 100, fatigue REAL DEFAULT 100, health REAL DEFAULT 100,
 armour REAL DEFAULT 0, x REAL DEFAULT 0, y REAL DEFAULT 0, z REAL DEFAULT 0, a REAL DEFAULT 0,
 interior INTEGER DEFAULT 0, vw INTEGER DEFAULT 0, phone TEXT DEFAULT '', org INTEGER DEFAULT 0,
 org_rank INTEGER DEFAULT 0, family INTEGER DEFAULT 0, family_rank INTEGER DEFAULT 0,
 job INTEGER DEFAULT 0, wanted INTEGER DEFAULT 0, jail INTEGER DEFAULT 0, mute INTEGER DEFAULT 0,
 played INTEGER DEFAULT 0, lic_drive INTEGER DEFAULT 0, medcard INTEGER DEFAULT 0,
 rent_house INTEGER DEFAULT 0, fish_skill INTEGER DEFAULT 0, injured INTEGER DEFAULT 0,
 char_done INTEGER DEFAULT 0, org_skin INTEGER DEFAULT 0, warns INTEGER DEFAULT 0,
 theory INTEGER DEFAULT 0, ref_paid INTEGER DEFAULT 0, acc_slot0 INTEGER DEFAULT 0,
 acc_slot1 INTEGER DEFAULT 0, spawn_at INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS bans (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT COLLATE NOCASE, ip TEXT, until INTEGER, reason TEXT, admin TEXT);
CREATE TABLE IF NOT EXISTS items (acc INTEGER, slot INTEGER, item INTEGER, amount INTEGER, PRIMARY KEY(acc, slot));
CREATE TABLE IF NOT EXISTS storage (otype INTEGER, oid INTEGER, slot INTEGER, item INTEGER, amount INTEGER, PRIMARY KEY(otype, oid, slot));
CREATE TABLE IF NOT EXISTS passports (acc INTEGER PRIMARY KEY, number TEXT, birth_city TEXT, marital TEXT, issued TEXT);
CREATE TABLE IF NOT EXISTS vehicles (
 id INTEGER PRIMARY KEY AUTOINCREMENT, owner INTEGER, model INTEGER, c1 INTEGER, c2 INTEGER,
 x REAL, y REAL, z REAL, a REAL, fuel REAL DEFAULT 40, locked INTEGER DEFAULT 1,
 impound INTEGER DEFAULT 0, mileage REAL DEFAULT 0, nitro INTEGER DEFAULT 0, wheels INTEGER DEFAULT 0, price INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS houses (
 id INTEGER PRIMARY KEY AUTOINCREMENT, owner INTEGER DEFAULT 0, price INTEGER, rent INTEGER,
 x REAL, y REAL, z REAL, class INTEGER, locked INTEGER DEFAULT 1, debt INTEGER DEFAULT 0, for_rent INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS businesses (
 id INTEGER PRIMARY KEY AUTOINCREMENT, type INTEGER, name TEXT, owner INTEGER DEFAULT 0, price INTEGER,
 x REAL, y REAL, z REAL, stock INTEGER DEFAULT 500, balance INTEGER DEFAULT 0, markup INTEGER DEFAULT 100
);
CREATE TABLE IF NOT EXISTS orgs (id INTEGER PRIMARY KEY, name TEXT, type INTEGER, leader INTEGER DEFAULT 0, bank INTEGER DEFAULT 50000, mats INTEGER DEFAULT 1000);
CREATE TABLE IF NOT EXISTS org_ranks (org INTEGER, rank INTEGER, name TEXT, salary INTEGER, skin INTEGER, PRIMARY KEY(org, rank));
CREATE TABLE IF NOT EXISTS families (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE COLLATE NOCASE, leader INTEGER, bank INTEGER DEFAULT 0, created TEXT);
CREATE TABLE IF NOT EXISTS quests (id INTEGER PRIMARY KEY, code TEXT, title TEXT, npc TEXT);
CREATE TABLE IF NOT EXISTS quest_steps (
 quest INTEGER, step INTEGER, chapter INTEGER, path TEXT DEFAULT '', type TEXT, key TEXT, arg TEXT DEFAULT '*',
 target INTEGER DEFAULT 1, title TEXT, hint TEXT, loc TEXT DEFAULT '', r_money INTEGER DEFAULT 0, r_exp INTEGER DEFAULT 0,
 PRIMARY KEY(quest, step)
);
CREATE TABLE IF NOT EXISTS player_quests (acc INTEGER, quest INTEGER, step INTEGER DEFAULT 1, progress INTEGER DEFAULT 0, status INTEGER DEFAULT 0, path TEXT DEFAULT '', PRIMARY KEY(acc, quest));
CREATE TABLE IF NOT EXISTS contacts (acc INTEGER, name TEXT, number TEXT);
CREATE TABLE IF NOT EXISTS sms (id INTEGER PRIMARY KEY AUTOINCREMENT, from_no TEXT, to_no TEXT, text TEXT, date TEXT);
CREATE TABLE IF NOT EXISTS achievements (acc INTEGER, code TEXT, date TEXT, PRIMARY KEY(acc, code));
CREATE TABLE IF NOT EXISTS locations (code TEXT PRIMARY KEY, x REAL, y REAL, z REAL, a REAL DEFAULT 0, interior INTEGER DEFAULT 0, vw INTEGER DEFAULT 0, title TEXT);
CREATE TABLE IF NOT EXISTS logs (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT, type TEXT, acc TEXT, text TEXT);
CREATE TABLE IF NOT EXISTS fines (id INTEGER PRIMARY KEY AUTOINCREMENT, acc INTEGER, amount INTEGER, reason TEXT, officer TEXT, paid INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS news (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT, author TEXT, text TEXT);
CREATE INDEX IF NOT EXISTS idx_items_acc ON items(acc);
CREATE INDEX IF NOT EXISTS idx_veh_owner ON vehicles(owner);
