-- 2.2: живой мир — NPC, 25 новых квестов по всему штату, больница изнутри, поезда, новые работы, рассрочка
ALTER TABLE quests ADD COLUMN giver TEXT DEFAULT '';
ALTER TABLE quests ADD COLUMN req_quest INTEGER DEFAULT 0;
ALTER TABLE quests ADD COLUMN req_level INTEGER DEFAULT 0;
ALTER TABLE quests ADD COLUMN city TEXT DEFAULT '';
ALTER TABLE quests ADD COLUMN descr TEXT DEFAULT '';
ALTER TABLE quest_steps ADD COLUMN say TEXT DEFAULT '';
ALTER TABLE accounts ADD COLUMN debt INTEGER DEFAULT 0;
CREATE TABLE IF NOT EXISTS npcs (code TEXT PRIMARY KEY, name TEXT, skin INTEGER, loc TEXT, anim TEXT DEFAULT '', greet TEXT DEFAULT '');
-- больница изнутри (интерьер 3, мир 7)
INSERT OR REPLACE INTO locations VALUES ('hospital_in',390.17,173.81,1008.38,90,3,7,'Выход из больницы');
INSERT OR REPLACE INTO locations VALUES ('hospital_spawn',381.00,173.70,1008.38,90,3,7,'Палата больницы');
INSERT OR REPLACE INTO locations VALUES ('med_reception',377.00,173.70,1008.38,90,3,7,'Больница');
INSERT OR REPLACE INTO locations VALUES ('med_ther',361.80,182.70,1008.38,0,3,7,'Больница');
INSERT OR REPLACE INTO locations VALUES ('med_eye',359.70,173.60,1008.38,90,3,7,'Больница');
INSERT OR REPLACE INTO locations VALUES ('med_lab',369.00,173.70,1008.38,0,3,7,'Больница');
UPDATE locations SET title='Больница All Saints' WHERE code='hospital';
-- точки квестов, вокзалов и работ (сняты с путевых узлов GTA SA)
INSERT OR REPLACE INTO locations VALUES ('countryside_stop',674.10,-579.50,16.40,0,0,0,'Автостанция Диллимора');
INSERT OR REPLACE INTO locations VALUES ('electric_spawn',2066.50,1193.10,10.60,0,0,0,'Фургоны электриков');
INSERT OR REPLACE INTO locations VALUES ('job_electric',2052.25,1177.10,10.60,0,0,0,'Работа: электрик');
INSERT OR REPLACE INTO locations VALUES ('job_farmer',-14.88,106.75,3.12,0,0,0,'Работа: фермер');
INSERT OR REPLACE INTO locations VALUES ('ls_station',1756.12,-1945.25,13.50,0,0,0,'Вокзал Юнити');
INSERT OR REPLACE INTO locations VALUES ('lv_station',2845.38,1290.75,11.38,0,0,0,'Вокзал Лас-Вентураса');
INSERT OR REPLACE INTO locations VALUES ('q_angelpine',-2148.50,-2398.62,30.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_ashot2',1693.12,-1885.25,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_bayside',-2495.25,2323.62,4.88,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_blueberry',225.50,-150.12,1.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_blueberry2',240.10,-116.60,1.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_bobby',714.12,-478.50,16.25,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_busdisp',1768.12,-1885.25,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_cat1',2383.62,-1724.50,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_cat2',2281.25,-1647.50,15.12,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_cat3',2229.38,-1725.00,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_chiliad',-2306.25,-1661.25,483.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_dillimore_mkt',660.38,-592.75,16.25,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_elq',-1503.75,2593.88,55.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_farm1',-53.75,14.75,3.00,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_farm2',-101.12,53.12,3.00,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_farm3',-14.88,106.75,3.12,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_farm4',52.20,81.60,2.00,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_fortcarson',-154.88,1105.62,19.62,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_glen',1963.50,-1203.50,25.62,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_ls_airport',1903.38,-2266.38,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_ls_beach',363.00,-1797.38,8.12,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_lv_airport',1679.50,1450.62,10.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_lv_calig',2169.62,1674.88,10.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_lv_dragons',2032.12,1003.12,10.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_lv_light1',2101.25,1515.75,10.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_lv_light2',2226.62,1885.88,10.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_lv_light3',1950.00,2120.75,10.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_lv_mansion',2549.12,701.00,10.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_lv_police',2290.50,2427.50,10.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_lv_redsands',1743.00,776.62,10.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_lv_strip',2030.88,1299.75,10.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_market',819.38,-1349.00,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_montgomery',1365.88,440.88,20.00,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_og',2512.25,-1671.75,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_palomino',2336.25,38.75,26.38,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_semyon',835.38,-1992.25,12.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_sf_china',-2206.75,697.25,49.38,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_sf_china2',-2153.75,651.25,52.25,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_sf_cityhall',-2698.75,384.25,4.25,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_sf_fin',-1804.38,897.88,24.88,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_sf_gant',-2679.75,1298.25,7.12,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_sf_garage',-2014.25,169.00,27.62,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_sf_hosp',-2657.75,633.00,14.38,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_sf_pier',-1658.25,1290.50,7.12,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_shaw1',1477.88,-1741.50,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_shaw2',2042.00,-1705.88,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_shaw3',1187.62,-1339.62,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_taxidisp',1772.88,-1939.12,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_unity_ticket',1745.62,-1949.38,14.00,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_verdant',395.50,2550.62,16.38,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_vinewood',1391.62,-908.88,35.75,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_vm_part1',395.50,2550.62,16.38,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_vm_part2',425.62,2569.75,16.25,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_vm_part3',304.75,2560.50,16.25,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('q_zina',2438.25,-1666.25,13.50,0,0,0,'');
INSERT OR REPLACE INTO locations VALUES ('sf_station',-1972.12,119.50,27.62,0,0,0,'Вокзал Сан-Фиерро');
INSERT OR REPLACE INTO npcs VALUES ('ashot','Ашот',168,'q_ashot2','smoke','Шаурма свежая, брат! Заходи ещё, для тебя всегда скидка.');
INSERT OR REPLACE INTO npcs VALUES ('zina','Баба Зина',89,'q_zina','look','Ох, внучок, ноги уже не те... Всё вокруг меняется, только Гантон прежний.');
INSERT OR REPLACE INTO npcs VALUES ('taxi_disp','Диспетчер Люда',150,'q_taxidisp','phone','Такси «Godjo Cab», слушаю! А, это ты. Машин свободных пока нет.');
INSERT OR REPLACE INTO npcs VALUES ('bus_disp','Механик Палыч',50,'q_busdisp','work','Автобусы — они как люди: если не ухаживать, ломаются.');
INSERT OR REPLACE INTO npcs VALUES ('semyon','Дед Семён',158,'q_semyon','fish','Тише ты, рыбу распугаешь! Садись рядом, только молча.');
INSERT OR REPLACE INTO npcs VALUES ('og','Свит',270,'q_og','lean','Grove Street — дом. Не забывай, откуда ты, брат.');
INSERT OR REPLACE INTO npcs VALUES ('shaw','Доктор Шоу',70,'q_shaw3','smoke','Пять минут перерыва за двенадцать часов смены... Что-то срочное?');
INSERT OR REPLACE INTO npcs VALUES ('director','Режиссёр Тим',17,'q_vinewood','arms','Свет! Камера! Нет-нет, ты не в кадре, отойди.');
INSERT OR REPLACE INTO npcs VALUES ('pilot','Пилот Макс',61,'q_ls_airport','look','Сегодня рейсов нет — туман над заливом. А поезда ходят.');
INSERT OR REPLACE INTO npcs VALUES ('mihalych','Фермер Михалыч',158,'q_farm1','work','Земля, она труд любит. И руки крепкие.');
INSERT OR REPLACE INTO npcs VALUES ('bobby','Механик Бобби',50,'q_bobby','work','Диллимор маленький, но машины тут ломаются как везде.');
INSERT OR REPLACE INTO npcs VALUES ('nancy','Заправщица Нэнси',157,'q_montgomery','look','Заправка «У Нэнси» — лучший кофе на трассе. Правда, кофемашина сломана.');
INSERT OR REPLACE INTO npcs VALUES ('sheriff','Шериф Коллинз',283,'q_palomino','arms','В моём округе тихо. Пока что.');
INSERT OR REPLACE INTO npcs VALUES ('hunter','Охотник Жора',162,'q_angelpine','smoke','На Чилиаде медведей нет. Но есть кое-что поинтереснее.');
INSERT OR REPLACE INTO npcs VALUES ('mayor_fc','Мэр Форт-Карсона',161,'q_fortcarson','look','Наш городок маленький, но гордый. Если бы ещё вода из крана текла...');
INSERT OR REPLACE INTO npcs VALUES ('tony','Механик Тони',8,'q_verdant','work','Verdant Meadows — бывший аэродром. Тут всё, что летало, теперь ржавеет.');
INSERT OR REPLACE INTO npcs VALUES ('ksenia','Ксения',192,'q_sf_garage','work','Гараж в Догерти — мой. Перешёл от отца. Масло, бензин и никакого тумана в голове.');
INSERT OR REPLACE INTO npcs VALUES ('li','Мистер Ли',117,'q_sf_china','arms','В Чайнатауне всё имеет цену. И уважение — тоже.');
INSERT OR REPLACE INTO npcs VALUES ('harry','Рыбак Гарри',35,'q_sf_pier','fish','Залив Сан-Фиерро холодный, зато рыба жирная.');
INSERT OR REPLACE INTO npcs VALUES ('frank','Чиновник Фрэнк',147,'q_sf_cityhall','phone','Да-да, отчёт будет к пятнице... Простите, вы ко мне?');
INSERT OR REPLACE INTO npcs VALUES ('lex','Промоутер Лекс',296,'q_lv_strip','phone','Вегас никогда не спит! Хотя сегодня половина вывесок спит.');
INSERT OR REPLACE INTO npcs VALUES ('van','Крупье Ван',171,'q_lv_dragons','arms','Ставки сделаны, ставок больше нет. Шучу. Чем помочь?');
INSERT OR REPLACE INTO npcs VALUES ('reed','Детектив Рид',280,'q_lv_police','smoke','В этом городе у всех есть секреты. Моя работа — их находить.');
INSERT OR REPLACE INTO npcs VALUES ('gosha','Гоша',113,'q_lv_mansion','sit','Я много лет жду, когда кто-нибудь придёт от Вовы.');
INSERT OR REPLACE INTO npcs VALUES ('oleg','Бригадир Олег',260,'job_electric','work','Электрики нужны всегда — в Вегасе каждая вывеска на счету. Отдел кадров — тут же.');
UPDATE quests SET city='Лос-Сантос', giver='' WHERE id=1;
UPDATE quest_steps SET hint='Больница All Saints: вход, регистратура (ALT). Нет денег — бесплатно по полису ОМС.' WHERE quest=1 AND step=8;
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (2,'shawarma','Шаурма на колёсах','Ашот','ashot',0,1,'Лос-Сантос','Слушай, брат, курьер опять заболел, а заказы горят! Отнеси два заказа — офис на Першинг-сквер и дом в Глен-парке. Заплачу как своему.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (2,1,0,'','talk','ashot','*',1,'Возьми заказы у Ашота','Ашот у своего ларька у вокзала.','',0,0,'Держи пакеты. Горячее — в офис на Першинг-сквер, второе — в Глен-парк. Не урони, это мой фирменный соус!');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (2,2,0,'','goto','','*',1,'Отнеси заказ на Першинг-сквер','Офисный центр у площади Першинг. Метка на карте.','q_shaw1',0,10,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (2,3,0,'','goto','','*',1,'Отнеси заказ в Глен-парк','Жилой квартал у парка на севере района.','q_glen',0,10,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (2,4,0,'','talk','ashot','*',1,'Вернись к Ашоту за оплатой','Ларёк у вокзала Юнити.','',150,40,'Клиенты звонили — сказали, курьер вежливый и быстрый! Держи деньги и шаурму сверху. Будет работа — позову.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (3,'cat','Где же Мурзик?','Баба Зина','zina',0,1,'Лос-Сантос','Внучок, беда! Мурзик мой третий день домой не идёт. Он рыжий, толстый и вредный. Поищи во дворах Гантона, а? Я пирожков напеку.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (3,1,0,'','talk','zina','*',1,'Выслушай бабу Зину','Баба Зина живёт в Гантоне.','',0,0,'Последний раз видела его у гаражей, на соседней улице. Он любит греться на капотах.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (3,2,0,'','goto','','*',1,'Проверь гаражи на соседней улице','Мурзик любит греться на капотах. Метка на карте.','q_cat1',0,10,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (3,3,0,'','mini','find','1',1,'Найди кота в кустах','Ищите рыжий хвост: кликайте по подозрительным местам.','q_cat2',0,20,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (3,4,0,'','talk','zina','*',1,'Принеси Мурзика бабе Зине','Возвращайтесь в Гантон.','',120,40,'Мурзик! Живой! Ах ты ж разбойник... Спасибо, внучок. Вот, держи пирожки и немного денег — на проезд.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (4,'taxi_first','Первый рейс','Диспетчер Люда','taxi_disp',0,2,'Лос-Сантос','Водителей не хватает — половина ушла в Вегас за длинным долларом. Устраивайся к нам таксистом и отвези хотя бы трёх клиентов. Премию выпишу.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (4,1,0,'','talk','taxi_disp','*',1,'Поговори с диспетчером такси','Таксопарк у вокзала Юнити.','',0,0,'Права есть? Отлично. Отдел кадров рядом — ALT у стойки. Клиенты голосуют прямо на тротуарах.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (4,2,0,'','event','job_join','taxi',1,'Устройся таксистом','Отдел кадров таксопарка у вокзала.','job_taxi',0,0,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (4,3,0,'','event','taxi_fare','*',3,'Отвези трёх клиентов','Подъезжайте к людям, голосующим у дороги. Не бейте машину — пассажиры этого не любят.','',0,0,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (4,4,0,'','talk','taxi_disp','*',1,'Отчитайся диспетчеру','Таксопарк у вокзала Юнити.','',300,60,'Жалоб ноль, чаевые есть — да ты прирождённый таксист! Вот премия.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (5,'bus_night','Ночной маршрут','Механик Палыч','bus_disp',0,2,'Лос-Сантос','Водитель городского маршрута ушёл в отпуск, а люди на остановках ждут. Проедешь круг по городу? Автобус заправлен, я проверил тормоза. Наверное.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (5,1,0,'','talk','bus_disp','*',1,'Поговори с механиком Палычем','Автобусный парк у вокзала.','',0,0,'Устраивайся в отдел кадров, бери «Городской маршрут». Останавливайся на каждой остановке — люди мёрзнут.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (5,2,0,'','event','job_join','bus',1,'Устройся водителем автобуса','Отдел кадров автобусного парка.','job_bus',0,0,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (5,3,0,'','event','bus_lap','city',1,'Проедь полный круг городского маршрута','Остановки отмечены на маршруте, на них ждут пассажиры.','',0,0,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (5,4,0,'','talk','bus_disp','*',1,'Верни автобус Палычу','Автобусный парк у вокзала.','',400,80,'Ни царапины! Знаешь, а приходи к нам насовсем. Держи премию.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (6,'doctor_bag','Врачебная тайна','Доктор Шоу','shaw',0,1,'Лос-Сантос','Пациентка забыла на пляже мою сумку с лекарствами — я дал ей подержать, пока мы ждали скорую. Там инсулин для детского отделения. Найди её, пожалуйста.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (6,1,0,'','talk','shaw','*',1,'Поговори с доктором Шоу','Доктор курит у входа в больницу All Saints.','',0,0,'Пляж Санта-Мария, у спасательной вышки. Чёрная сумка с красным крестом. Быстрее, прошу!');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (6,2,0,'','mini','find','2',1,'Найди сумку доктора на пляже','Осмотрите пляж у вышки спасателей.','q_ls_beach',0,30,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (6,3,0,'','talk','shaw','*',1,'Верни сумку доктору Шоу','Больница All Saints.','',200,60,'Всё на месте, даже ампулы целы! Ты спас мне смену — и, возможно, чью-то жизнь. Если будут проблемы со здоровьем — заходи без очереди.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (7,'grove','Свои люди','Свит','og',0,2,'Лос-Сантос','Ballas опять закрасили наш тэг на стене у рынка. Это неуважение, брат. Восстанови — и Grove тебя запомнит.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (7,1,0,'','talk','og','*',1,'Поговори со Свитом','Свит у своего дома на Grove Street.','',0,0,'Баллончик возьми у меня. Стена у рынка Маркет. Рисуй быстро и уходи — без стрельбы.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (7,2,0,'','mini','seq','2',1,'Нарисуй тэг Grove на стене','Повторите движения баллончиком (стрелки).','q_market',0,30,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (7,3,0,'','talk','og','*',1,'Вернись к Свиту','Grove Street, Гантон.','',250,60,'Видел, видел. Зелёный — лучший цвет в этом городе. Ты свой, брат.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (8,'vinewood','Звёзды Вайнвуда','Режиссёр Тим','director',0,2,'Лос-Сантос','Мой фотограф сбежал со съёмок! Нужен кадр знаменитой надписи на закате, пока свет хороший. Камера у меня — руки нужны твои.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (8,1,0,'','talk','director','*',1,'Поговори с режиссёром','Режиссёр Тим на холмах Вайнвуда.','',0,0,'Камеру держи вот так. Встань у обзорной точки Глен-парка — оттуда надпись видна целиком. И не трясись!');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (8,2,0,'','mini','photo','2',1,'Сделай идеальный кадр','Поймайте момент, когда надпись в рамке.','q_glen',0,30,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (8,3,0,'','talk','director','*',1,'Отдай камеру режиссёру','Холмы Вайнвуда.','',300,60,'Это... гениально. Ты точно не фотограф? Держи гонорар. Может, ещё и в кино тебя снимем.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (9,'letter_farm','Письмо для Михалыча','Механик Палыч','bus_disp',5,2,'Деревня','Мой брат Михалыч фермерствует у Блуберри. Телефона у него нет — принципиально. Отвези ему письмо и посылку, а? Пригородный автобус или поезд до Диллимора.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (9,1,0,'','talk','bus_disp','*',1,'Возьми письмо у Палыча','Автобусный парк у вокзала.','',0,0,'Вот письмо и банка мёда. Касса на вокзале Юнити продаст билет до Диллимора, а там до фермы рукой подать.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (9,2,0,'','event','travel','country',1,'Доберись до Диллимора','Касса вокзала Юнити -> автостанция Диллимора. Можно и своим ходом.','ls_station',0,0,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (9,3,0,'','talk','mihalych','*',1,'Найди фермера Михалыча','Ферма к западу от Блуберри.','',200,60,'От Палыча? Ну наконец-то! Мёд... Помнит, значит, что я люблю. Садись, чаю попьём.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (10,'harvest','Урожай Михалыча','Фермер Михалыч','mihalych',9,2,'Деревня','Урожай поспел, а помощников нет — молодёжь вся в городе. Поможешь собрать кукурузу и тыквы? Заплачу и молока налью.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (10,1,0,'','talk','mihalych','*',1,'Поговори с Михалычем','Ферма у Блуберри.','',0,0,'Кукурузное поле — за амбаром, тыквы — у дороги. Работай быстро, пока не стемнело.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (10,2,0,'','mini','mash','2',1,'Собери кукурузу','Быстро жмите ПРОБЕЛ, чтобы набрать корзину.','q_farm2',0,20,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (10,3,0,'','mini','mash','3',1,'Собери тыквы','Тыквы тяжёлые — жмите быстрее!','q_farm4',0,20,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (10,4,0,'','talk','mihalych','*',1,'Отнеси урожай Михалычу','Ферма у Блуберри.','',350,80,'Вот это урожай! Держи деньги. А если понравилось — приходи работать, я в отделе кадров фермы всех беру.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (11,'big_fish','Дед Семён и большая рыба','Дед Семён','semyon',0,1,'Лос-Сантос','Внук приезжает, а мне похвастаться нечем — не клюёт! Налови мне пару рыбёшек, а я ему скажу, что сам. Только тсс!');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (11,1,0,'','talk','semyon','*',1,'Поговори с дедом Семёном','Дед Семён на пирсе Санта-Марии.','',0,0,'Удочку купи в 24/7, наживку там же. Встань у края пирса и /fish. Три рыбы, любые.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (11,2,0,'','item','fish_s','*',3,'Поймай 3 мелкие рыбы','Рыбалка на пирсе: /fish у края, удочка и наживка — в 24/7.','fishing',0,0,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (11,3,0,'','give','semyon','fish_s',3,'Отдай рыбу деду Семёну','Пирс Санта-Марии.','',250,60,'Вот это улов! Внук обзавидуется. Держи, заслужил — и никому ни слова.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (12,'bobby','Мастерская Бобби','Механик Бобби','bobby',9,2,'Деревня','У рынка Диллимора встал генератор, а без него холодильники с продуктами потекут. Руки у меня в масле по локоть — поможешь с проводкой?');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (12,1,0,'','talk','bobby','*',1,'Поговори с механиком Бобби','Мастерская в Диллиморе.','',0,0,'Щиток генератора у рынка. Красный к красному, синий к синему — справишься.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (12,2,0,'','mini','wires','2',1,'Почини генератор у рынка','Соедините провода одного цвета.','q_dillimore_mkt',0,30,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (12,3,0,'','talk','bobby','*',1,'Вернись к Бобби','Мастерская в Диллиморе.','',300,60,'Слышу — загудел! Держи деньги. И передай Нэнси в Монтгомери, что я помню про её канистры.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (13,'nancy','Бензин для Нэнси','Заправщица Нэнси','nancy',12,2,'Деревня','Бензовоз не приехал уже неделю, а шериф Коллинз обещал одолжить канистры из участка. Съезди к нему в Паломино-Крик, пожалуйста.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (13,1,0,'','talk','nancy','*',1,'Поговори с Нэнси','Заправка в Монтгомери.','',0,0,'Шериф в Паломино-Крик, у участка. Скажи, что от Нэнси — он поймёт.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (13,2,0,'','talk','sheriff','*',1,'Забери канистры у шерифа','Паломино-Крик, у полицейского участка.','',0,0,'Для Нэнси? Конечно. Только передай, что кофе у неё всё ещё отвратительный. Шучу. Наполовину.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (13,3,0,'','talk','nancy','*',1,'Привези канистры Нэнси','Заправка в Монтгомери.','',300,60,'Ты спаситель! Дальнобойщики уже бунтовать собирались. Держи, и кофе за счёт заведения.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (14,'sheriff','Шериф Паломино','Шериф Коллинз','sheriff',13,3,'Деревня','В заброшенном доме у Блуберри кто-то ночует и ворует у фермеров. Мои помощники в отпуске. Осмотришь место? Только улики, без геройства.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (14,1,0,'','talk','sheriff','*',1,'Получи задание у шерифа','Паломино-Крик.','',0,0,'Дом на окраине Блуберри, у реки. Ищи следы, вещи, что угодно. Вернёшься — расскажешь.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (14,2,0,'','mini','find','3',1,'Найди улики у заброшенного дома','Осмотрите двор: следы, мешок, окурки.','q_blueberry2',0,40,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (14,3,0,'','talk','sheriff','*',1,'Доложи шерифу','Паломино-Крик.','',400,80,'Мешок с фермерскими инструментами и билет из Энджел-Пайна... Ясно, это бродяга с гор. Спасибо, помощник.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (15,'chiliad','Тайник на Чилиаде','Охотник Жора','hunter',14,3,'Деревня','Мой дед был геодезистом и спрятал на горе Чилиад ящик с картами старых шахт. Код замка он мне сказал перед смертью — да я забыл. Поможешь вспомнить на месте?');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (15,1,0,'','talk','hunter','*',1,'Поговори с охотником Жорой','Энджел-Пайн.','',0,0,'Вершина Чилиада, у смотровой площадки. Цифры дед выцарапал на камнях — запомни и набери.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (15,2,0,'','mini','code','3',1,'Открой тайник на вершине','Запомните код и наберите его.','q_chiliad',0,40,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (15,3,0,'','talk','hunter','*',1,'Принеси карты Жоре','Энджел-Пайн.','',600,100,'Карты шахт! Дед был прав — тут и старый карьер, и пещеры. Держи свою долю.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (16,'sf_calls','Сан-Фиерро зовёт','Пилот Макс','pilot',4,3,'Сан-Фиерро','Рейсы отменили, а сестре в Сан-Фиерро срочно нужна помощь в гараже. Съездишь поездом вместо меня? Билет оплачу.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (16,1,0,'','talk','pilot','*',1,'Поговори с пилотом Максом','Аэропорт Лос-Сантоса.','',0,0,'Поезд с вокзала Юнити. Гараж в Догерти, сестру зовут Ксения. Скажи, что я скоро прилечу.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (16,2,0,'','event','travel','sf',1,'Доберись до Сан-Фиерро','Касса вокзала Юнити -> Сан-Фиерро.','ls_station',0,0,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (16,3,0,'','talk','ksenia','*',1,'Найди Ксению в гараже Догерти','Гараж у вокзала Сан-Фиерро.','',300,60,'Макс прислал? Ну хоть кто-то. Добро пожаловать в Сан-Фиерро — тут холмы, туман и вечно нет запчастей.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (17,'doherty','Гараж в Догерти','Ксения','ksenia',16,3,'Сан-Фиерро','Фургон клиента встал посреди Чайнатауна — проводка сгорела. Съезди, почини на месте, а я пока закажу запчасти.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (17,1,0,'','talk','ksenia','*',1,'Поговори с Ксенией','Гараж в Догерти.','',0,0,'Фургон у ворот Чайнатауна. Схема простая — цвет к цвету.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (17,2,0,'','mini','wires','3',1,'Почини фургон в Чайнатауне','Соедините провода одного цвета.','q_sf_china2',0,40,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (17,3,0,'','talk','ksenia','*',1,'Вернись в гараж','Гараж в Догерти.','',400,80,'Клиент доволен, я тоже. У тебя руки откуда надо. Держи.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (18,'chinatown','Чайнатаун','Мистер Ли','li',17,3,'Сан-Фиерро','Корабль с фейерверками к празднику пришёл на пирс, а грузчики разбежались. Поможешь разгрузить? Аккуратно — порох не любит спешки.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (18,1,0,'','talk','li','*',1,'Поговори с мистером Ли','Чайнатаун, Сан-Фиерро.','',0,0,'Пирс на севере, у залива. Ящики подавай в ритме — я покажу движения.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (18,2,0,'','mini','seq','3',1,'Разгрузи фейерверки','Повторите последовательность движений.','q_sf_pier',0,40,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (18,3,0,'','talk','li','*',1,'Вернись к мистеру Ли','Чайнатаун.','',450,80,'Ни один ящик не взорвался — это хороший знак. Уважение Чайнатауна дорого стоит. Держи.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (19,'pier39','Пирс Гарри','Рыбак Гарри','harry',16,2,'Сан-Фиерро','Говорят, в Лос-Сантосе рыба другая — сладкая. Не верю! Привези мне пару средних рыбин из Санта-Марии, сравним.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (19,1,0,'','talk','harry','*',1,'Поговори с рыбаком Гарри','Северный пирс Сан-Фиерро.','',0,0,'Две средние рыбины. Пирс Санта-Марии в Лос-Сантосе, /fish. Посмотрим, чья рыба лучше.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (19,2,0,'','item','fish_m','*',2,'Поймай 2 средние рыбы','Рыбалка: пирс Санта-Марии, /fish.','fishing',0,0,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (19,3,0,'','give','harry','fish_m',2,'Отдай рыбу Гарри','Северный пирс Сан-Фиерро.','',400,60,'Хм... Ладно, признаю — неплохо. Но наша жирнее! Держи за труды.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (20,'gant','Мост Гант','Чиновник Фрэнк','frank',18,4,'Сан-Фиерро','Инспектор заболел, а отчёт о состоянии моста Гант нужен завтра. Сфотографируй трещины у опор и отнеси снимки в Финансовый район.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (20,1,0,'','talk','frank','*',1,'Поговори с чиновником Фрэнком','Мэрия Сан-Фиерро.','',0,0,'Опоры у южного въезда на мост. Снимки — в банк в Финансовом районе, там комиссия.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (20,2,0,'','mini','photo','3',1,'Сфотографируй опоры моста','Поймайте кадр, когда трещина в рамке.','q_sf_gant',0,40,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (20,3,0,'','goto','','*',1,'Отнеси снимки в Финансовый район','Банк в центре Сан-Фиерро.','q_sf_fin',0,20,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (20,4,0,'','talk','frank','*',1,'Вернись к Фрэнку','Мэрия Сан-Фиерро.','',500,100,'Комиссия довольна, мост простоит ещё сто лет. Ну, лет десять. Держи гонорар.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (21,'lv_lights','Огни Лас-Вентураса','Промоутер Лекс','lex',16,4,'Лас-Вентурас','Три вывески на Стрипе погасли прямо перед шоу! Электрики на вызовах. Ты ведь умеешь с проводами? Плачу по-вегасски.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (21,1,0,'','talk','lex','*',1,'Поговори с промоутером Лексом','Стрип, Лас-Вентурас.','',0,0,'Первая вывеска у казино на юге Стрипа, вторая у Калигулы, третья на севере. Время — деньги!');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (21,2,0,'','mini','wires','3',1,'Почини первую вывеску','Соедините провода одного цвета.','q_lv_light1',0,30,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (21,3,0,'','mini','wires','3',1,'Почини вторую вывеску','Соедините провода одного цвета.','q_lv_light2',0,30,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (21,4,0,'','mini','wires','4',1,'Почини третью вывеску','Быстрее — шоу через минуту!','q_lv_light3',0,30,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (21,5,0,'','talk','lex','*',1,'Вернись к Лексу','Стрип.','',700,120,'Сияет! Ты спас шоу. Держи — и подумай про работу электрика, у Олега всегда есть вызовы.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (22,'dragon','Фишка дракона','Крупье Ван','van',21,4,'Лас-Вентурас','Из сейфа казино пропала коллекционная фишка «Золотой дракон». Подозреваю своих. Узнай код сейфа в Калигуле — там лежит копия журнала.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (22,1,0,'','talk','van','*',1,'Поговори с крупье Ваном','Казино «Четыре дракона».','',0,0,'Служебный вход в Калигулу. Код журнала меняют каждый день — увидишь цифры, запомни.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (22,2,0,'','mini','code','4',1,'Узнай код из журнала','Запомните код и наберите его.','q_lv_calig',0,40,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (22,3,0,'','goto','','*',1,'Встреться с информатором в Ред-Сэндс','Информатор ждёт у отеля.','q_lv_redsands',0,20,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (22,4,0,'','talk','van','*',1,'Вернись к Вану','Казино «Четыре дракона».','',600,100,'Значит, это был ночной менеджер... Фишка вернётся. Держи награду и молчи.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (23,'bayside','Свидетель из Бэйсайда','Детектив Рид','reed',21,5,'Лас-Вентурас','Есть свидетель угона — живёт в Бэйсайде, за мостом на севере Сан-Фиерро. Привези его показания и сфотографируй машину у Эль-Кебрадос.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (23,1,0,'','talk','reed','*',1,'Поговори с детективом Ридом','Полиция Лас-Вентураса.','',0,0,'Бэйсайд — маленький городок у залива. Свидетель — рыбак. Потом Эль-Кебрадос, синий седан.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (23,2,0,'','goto','','*',1,'Найди свидетеля в Бэйсайде','Бэйсайд, у пристани.','q_bayside',0,30,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (23,3,0,'','mini','photo','4',1,'Сфотографируй номер машины','Поймайте кадр, когда номер в рамке.','q_elq',0,40,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (23,4,0,'','talk','reed','*',1,'Привези улики детективу','Полиция Лас-Вентураса.','',800,140,'Номер совпадает. Ты сделал за неделю то, что мы не могли полгода. Держи премию.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (24,'tony','Детали для Тони','Механик Тони','tony',21,4,'Пустыня','Собираю самолёт из того, что осталось на старом аэродроме. Нужны три детали — они где-то на свалке ангаров. Глаза у меня уже не те.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (24,1,0,'','talk','tony','*',1,'Поговори с механиком Тони','Verdant Meadows.','',0,0,'Карбюратор — у первого ангара, пропеллер — у вышки, свечи — у забора. Ищи внимательно.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (24,2,0,'','mini','find','3',1,'Найди карбюратор','Осмотрите хлам у ангара.','q_vm_part1',0,20,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (24,3,0,'','mini','find','3',1,'Найди пропеллер','Осмотрите место у вышки.','q_vm_part2',0,20,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (24,4,0,'','mini','find','4',1,'Найди свечи','Осмотрите забор.','q_vm_part3',0,20,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (24,5,0,'','talk','tony','*',1,'Принеси детали Тони','Verdant Meadows.','',700,120,'Все три! Через месяц она полетит, клянусь. Прокачу первым — а пока держи деньги.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (25,'water','Вода для Форт-Карсона','Мэр Форт-Карсона','mayor_fc',14,3,'Пустыня','Насос на водокачке опять встал, а в городке жара под сорок. Механика нет — может, ты разберёшься?');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (25,1,0,'','talk','mayor_fc','*',1,'Поговори с мэром Форт-Карсона','Центр Форт-Карсона.','',0,0,'Водокачка у старого аэродрома Verdant Meadows. Надо раскачать поршень и вовремя отпустить.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (25,2,0,'','mini','hold','3',1,'Запусти насос водокачки','Зажмите и отпустите в зелёной зоне.','q_verdant',0,30,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (25,3,0,'','talk','mayor_fc','*',1,'Вернись к мэру','Форт-Карсон.','',500,80,'Вода пошла! Весь город тебе благодарен. Держи — из городской казны, честно.');
INSERT OR REPLACE INTO quests (id,code,title,npc,giver,req_quest,req_level,city,descr) VALUES (26,'debt','Возвращение долга','Гоша','gosha',22,5,'Лас-Вентурас','Ты от Вовы... Я узнаю этот взгляд. Двадцать лет назад я подставил лучшего друга. Я не могу смотреть ему в глаза — но ты можешь передать моё письмо.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (26,1,0,'','talk','gosha','*',1,'Выслушай Гошу','Особняк на востоке Лас-Вентураса.','',0,0,'Вот письмо и деньги — всё, что я должен ему за гараж и годы. Скажи... скажи, что я был трусом. Пусть простит, если сможет.');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (26,2,0,'','event','travel','ls',1,'Вернись в Лос-Сантос','Поезд с вокзала Лас-Вентураса до Юнити.','lv_station',0,0,'');
INSERT OR REPLACE INTO quest_steps (quest,step,chapter,path,type,key,arg,target,title,hint,loc,r_money,r_exp,say) VALUES (26,3,0,'','event','talk','vova_gosha',1,'Передай письмо Дяде Вове','Дядя Вова у ночлежки под эстакадой.','vova',2000,300,'');
